# Generated by Django 5.1.2 on 2024-11-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='media/product_images%Y/%m/'),
            preserve_default=False,
        ),
    ]
