# Generated by Django 5.1.2 on 2024-10-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdedItem',
            new_name='OrderedItem',
        ),
    ]
