# Generated by Django 5.1.2 on 2024-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_qtd_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('S', 'Enviado'), ('F', 'Finalizado')], default='c', max_length=1),
        ),
    ]
